var searchData=
[
  ['c_0',['Fixed string search (&lt;span class=&quot;tt&quot;&gt;-c&lt;/span&gt;)',['../md_README.html#autotoc_md149',1,'']]],
  ['c_20and_20g_1',['Q: What&apos;s the difference between &lt;span class=&quot;tt&quot;&gt;-c&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;-g&lt;/span&gt;?',['../md_README.html#autotoc_md165',1,'']]],
  ['c_20r_2',['Regex search (&lt;span class=&quot;tt&quot;&gt;-c&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;-r&lt;/span&gt;)',['../md_README.html#autotoc_md150',1,'']]],
  ['cache_20flush_20utility_3',['Cache-Flush Utility',['../dir_13a41d9ad64fb9ae396cb953294783cf.html#autotoc_md119',1,'']]],
  ['cache_20flush_20utility_20optional_20for_20benchmarking_4',['Build Cache-Flush Utility (Optional - for benchmarking)',['../md_README.html#autotoc_md138',1,'']]],
  ['can_20i_20use_20it_20on_20network_20filesystems_20nfs_20cifs_5',['Q: Can I use it on network filesystems (NFS, CIFS)?',['../md_README.html#autotoc_md163',1,'']]],
  ['categories_20and_20responses_6',['Error Categories and Responses',['../md_ARCHITECTURE.html#autotoc_md42',1,'']]],
  ['change_20propagation_7',['Filesystem Change Propagation',['../md_ARCHITECTURE.html#autotoc_md20',1,'']]],
  ['cifs_8',['Q: Can I use it on network filesystems (NFS, CIFS)?',['../md_README.html#autotoc_md163',1,'']]],
  ['client_20ffind_20cpp_9',['ffind Client (ffind.cpp)',['../md_ARCHITECTURE.html#autotoc_md9',1,'']]],
  ['client_20response_20format_10',['Daemon-to-Client Response Format',['../md_ARCHITECTURE.html#autotoc_md24',1,'']]],
  ['client_20to_20daemon_20binary_20protocol_11',['Client-to-Daemon Binary Protocol',['../md_ARCHITECTURE.html#autotoc_md23',1,'']]],
  ['code_20network_20required_12',['Option 2: Download GCC Source Code (Network Required)',['../dir_13a41d9ad64fb9ae396cb953294783cf.html#autotoc_md101',1,'']]],
  ['code_20sections_13',['Security-Critical Code Sections',['../md_ARCHITECTURE.html#autotoc_md33',1,'']]],
  ['color_20output_14',['Color output',['../md_README.html#autotoc_md154',1,'']]],
  ['comparison_20with_20other_20tools_15',['Comparison with Other Tools',['../md_README.html#autotoc_md129',1,'']]],
  ['compile_16',['Compile',['../md_README.html#autotoc_md137',1,'']]],
  ['component_20descriptions_17',['Component Descriptions',['../md_ARCHITECTURE.html#autotoc_md8',1,'']]],
  ['component_20index_20benchmark_20results_18',['Path Component Index - Benchmark Results',['../md_BENCHMARK__RESULTS.html',1,'']]],
  ['conclusion_19',['Conclusion',['../md_benchmarks_2EXECUTION__EVIDENCE.html#autotoc_md96',1,'']]],
  ['conclusions_20',['Conclusions',['../md_BENCHMARK__RESULTS.html#autotoc_md81',1,'']]],
  ['content_20search_21',['2. Thread Pool for Content Search',['../md_ARCHITECTURE.html#autotoc_md48',1,'']]],
  ['content_20search_20methods_22',['Content search methods',['../md_README.html#autotoc_md148',1,'']]],
  ['contents_23',['Contents',['../md_ARCHITECTURE.html#autotoc_md2',1,'Table of Contents'],['../md_README.html#autotoc_md124',1,'Table of Contents']]],
  ['context_20lines_24',['Context lines',['../md_README.html#autotoc_md152',1,'']]],
  ['contributing_25',['Contributing',['../dir_13a41d9ad64fb9ae396cb953294783cf.html#autotoc_md120',1,'']]],
  ['copy_20file_20reading_20mmap_26',['4. Zero-Copy File Reading (mmap)',['../md_ARCHITECTURE.html#autotoc_md52',1,'']]],
  ['corpus_27',['Test Corpus',['../md_benchmarks_2EXECUTION__EVIDENCE.html#autotoc_md90',1,'']]],
  ['corpus_20not_20found_28',['&quot;Test corpus not found&quot;',['../dir_13a41d9ad64fb9ae396cb953294783cf.html#autotoc_md115',1,'']]],
  ['corpus_20setup_29',['Test Corpus Setup',['../dir_13a41d9ad64fb9ae396cb953294783cf.html#autotoc_md99',1,'']]],
  ['cpp_30',['cpp',['../md_ARCHITECTURE.html#autotoc_md9',1,'ffind Client (ffind.cpp)'],['../md_ARCHITECTURE.html#autotoc_md11',1,'ffind-daemon (ffind-daemon.cpp)']]],
  ['criteria_31',['Success Criteria',['../md_BENCHMARK__RESULTS.html#autotoc_md82',1,'']]],
  ['critical_20code_20sections_32',['Security-Critical Code Sections',['../md_ARCHITECTURE.html#autotoc_md33',1,'']]],
  ['current_20version_33',['Implemented (current version)',['../md_TODO.html#autotoc_md169',1,'']]],
  ['customizing_20benchmarks_34',['Customizing Benchmarks',['../dir_13a41d9ad64fb9ae396cb953294783cf.html#autotoc_md113',1,'']]]
];
