var searchData=
[
  ['s_20the_20difference_20between_20c_20and_20g_0',['Q: What&apos;s the difference between &lt;span class=&quot;tt&quot;&gt;-c&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;-g&lt;/span&gt;?',['../md_README.html#autotoc_md165',1,'']]],
  ['safety_20guarantees_1',['Thread Safety Guarantees',['../md_ARCHITECTURE.html#autotoc_md28',1,'']]],
  ['schema_20optional_20persistence_2',['SQLite Schema (Optional Persistence)',['../md_ARCHITECTURE.html#autotoc_md37',1,'']]],
  ['script_3',['Benchmark Script',['../dir_13a41d9ad64fb9ae396cb953294783cf.html#autotoc_md104',1,'']]],
  ['search_4',['2. Thread Pool for Content Search',['../md_ARCHITECTURE.html#autotoc_md48',1,'']]],
  ['search_20c_5',['Fixed string search (&lt;span class=&quot;tt&quot;&gt;-c&lt;/span&gt;)',['../md_README.html#autotoc_md149',1,'']]],
  ['search_20c_20r_6',['Regex search (&lt;span class=&quot;tt&quot;&gt;-c&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;-r&lt;/span&gt;)',['../md_README.html#autotoc_md150',1,'']]],
  ['search_20examples_7',['Search examples',['../md_README.html#autotoc_md144',1,'']]],
  ['search_20g_8',['Glob search (&lt;span class=&quot;tt&quot;&gt;-g&lt;/span&gt;)',['../md_README.html#autotoc_md151',1,'']]],
  ['search_20methods_9',['Content search methods',['../md_README.html#autotoc_md148',1,'']]],
  ['search_20multiple_20directories_10',['Q: How do I search multiple directories?',['../md_README.html#autotoc_md164',1,'']]],
  ['sections_11',['Security-Critical Code Sections',['../md_ARCHITECTURE.html#autotoc_md33',1,'']]],
  ['security_20architecture_12',['Security Architecture',['../md_ARCHITECTURE.html#autotoc_md30',1,'']]],
  ['security_20critical_20code_20sections_13',['Security-Critical Code Sections',['../md_ARCHITECTURE.html#autotoc_md33',1,'']]],
  ['security_20layers_14',['Security Layers',['../md_ARCHITECTURE.html#autotoc_md32',1,'']]],
  ['service_20management_15',['Service Management',['../md_README.html#autotoc_md156',1,'']]],
  ['setup_16',['Test Corpus Setup',['../dir_13a41d9ad64fb9ae396cb953294783cf.html#autotoc_md99',1,'']]],
  ['size_20operators_17',['Size operators',['../md_README.html#autotoc_md146',1,'']]],
  ['size_20units_18',['Size units',['../md_README.html#autotoc_md145',1,'']]],
  ['source_20code_20network_20required_19',['Option 2: Download GCC Source Code (Network Required)',['../dir_13a41d9ad64fb9ae396cb953294783cf.html#autotoc_md101',1,'']]],
  ['source_20repository_20',['Option 4: Use Any Large Source Repository',['../dir_13a41d9ad64fb9ae396cb953294783cf.html#autotoc_md103',1,'']]],
  ['specification_21',['Protocol Specification',['../md_ARCHITECTURE.html#autotoc_md22',1,'']]],
  ['sqlite_20persistence_22',['5. SQLite Persistence',['../md_ARCHITECTURE.html#autotoc_md16',1,'']]],
  ['sqlite_20persistence_20optional_23',['SQLite Persistence (Optional)',['../md_README.html#autotoc_md142',1,'']]],
  ['sqlite_20schema_20optional_20persistence_24',['SQLite Schema (Optional Persistence)',['../md_ARCHITECTURE.html#autotoc_md37',1,'']]],
  ['sqlite_20write_20ahead_20logging_20wal_25',['7. SQLite Write-Ahead Logging (WAL)',['../md_ARCHITECTURE.html#autotoc_md58',1,'']]],
  ['start_26',['Start',['../dir_13a41d9ad64fb9ae396cb953294783cf.html#autotoc_md98',1,'Quick Start'],['../md_README.html#autotoc_md133',1,'Quick Start']]],
  ['start_20the_20daemon_27',['Start the daemon',['../md_README.html#autotoc_md141',1,'']]],
  ['storage_20and_20persistence_28',['Storage and Persistence',['../md_ARCHITECTURE.html#autotoc_md35',1,'']]],
  ['strategy_29',['Error Handling Strategy',['../md_ARCHITECTURE.html#autotoc_md41',1,'']]],
  ['string_20search_20c_30',['Fixed string search (&lt;span class=&quot;tt&quot;&gt;-c&lt;/span&gt;)',['../md_README.html#autotoc_md149',1,'']]],
  ['strong_20performance_20areas_31',['Strong Performance Areas',['../md_benchmarks_2EXECUTION__EVIDENCE.html#autotoc_md93',1,'']]],
  ['structure_32',['Structure',['../md_ARCHITECTURE.html#autotoc_md36',1,'In-Memory Index Structure'],['../md_BENCHMARK__RESULTS.html#autotoc_md75',1,'Path Index Structure']]],
  ['success_20criteria_33',['Success Criteria',['../md_BENCHMARK__RESULTS.html#autotoc_md82',1,'']]],
  ['suite_34',['Full Benchmark Suite',['../md_BENCHMARK__RESULTS.html#autotoc_md73',1,'']]],
  ['summary_35',['Summary',['../md_BENCHMARK__RESULTS.html#autotoc_md69',1,'Executive Summary'],['../md_ARCHITECTURE.html#autotoc_md60',1,'Performance Benchmarks Summary']]],
  ['summary_20january_202026_36',['ffind TODO Summary - January 2026',['../md_TODO.html',1,'']]],
  ['system_20architecture_37',['System Architecture',['../md_ARCHITECTURE.html#autotoc_md6',1,'']]],
  ['system_20requirements_38',['System Requirements',['../dir_13a41d9ad64fb9ae396cb953294783cf.html#autotoc_md108',1,'']]]
];
